destination: _site
markdown: rdiscount
permalink: /:year/:month/:title.html
exclude: [Capfile, deploy.rb, Readme.md]
paginate: 6
paginate_path: "page:num"

events:
    - name: 'Metal Displacement Over Nistru 2016'
      url: http://vk.com/mdon2016
      location: Moldova, Vadul lui Vodă
      date: 2016-05-21 13:00:00

    - name: 'Burning Lands Metal GIG'
      url: http://vk.com/burning_lands_metal_gig
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2016-04-15 19:00:00

    - name: 'MARCH METAL CATS FEST V'
      url: http://vk.com/event111642668
      location: Киев, Арт-паб "Бочка на Подолi"
      date: 2016-03-26 19:00:00

    - name: '“ЧЕРТ” побери... 20 лет на сцене!'
      url: http://vk.com/event112232772
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2016-02-06 18:00:00

    - name: 'Lost Santa New Year Metal GIG'
      url: http://vk.com/event108754387
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-12-26 18:00:00

    - name: 'Deadbuzz: Act of Demolish'
      url: http://vk.com/deadbuzzgig
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-12-04 19:00:00

    - name: 'Thrash Eviscerator GIG'
      url: http://vk.com/event101470518
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-10-15 19:00:00

    - name: 'Пикник на Обочине 5'
      url: http://vk.com/picnik_na_obochine
      location: Обухов, оз. Триджерельне
      date: 2015-08-11 13:00:00

    - name: 'BLACK SEA METAL FESTIVAL 2015'
      url: http://vk.com/blackseametalfest
      location: Ильичевск, Парковая 15, "Metropolis Arena"
      date: 2015-07-17 17:00:00

    - name: 'Kiev Kills: River Metal Party'
      url: http://vk.com/kievkills_submarine
      location: Киев, Гидропарк, Теплоход "Каштан 5"
      date: 2015-07-12 18:00:00

    - name: 'Kiev Kills: Metal Birthday Session'
      url: http://vk.com/kievkills_metal_birthday
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-07-05 18:00:00

    - name: 'Total Revenge GIG'
      url: http://vk.com/event88535492
      location: Киев, Арт-паб "Бочка на Подолi"
      date: 2015-05-22 19:00:00

    - name: 'Iron Rain GIG'
      url: http://vk.com/event90450374
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-04-04 18:00:00

    - name: 'Благодійний Концерт Пам`яті "Небесної Сотні"'
      url: http://vk.com/event85217001
      location: Киев, пр.Победы 112, клуб "Бинго"
      date: 2015-02-22 17:00:00

    - name: 'CHAOTIC "FRIDAY 13`s PARTY" vol.2'
      url: https://vk.com/chaoticparty2
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-02-13 17:00:00

    - name: 'День рождения ЧЕРТА'
      url: http://vk.com/event86013845
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-02-07 17:00:00

    - name: 'Благотворительный концерт "Soldiers Rescue Session"'
      url: http://vk.com/soldiers_rescue_session
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2015-02-01 17:00:00

    - name: 'Kiev Kills: True Metal Edition'
      url: http://vk.com/kievkillstrue_metal_edition
      location: Киев, ул. Глыбочицкая 72, клуб "Тыква"
      date: 2015-01-07 17:00:00

    - name: 'Steel Guard GIG'
      url: http://vk.com/event77272929
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2014-10-25 17:00:00

    - name: 'Вогняний Лев (фестиваль вогню й перфоменсу у Львові)'
      url: http://vk.com/lviv_fire_fest
      location: Львiв, парк "Погулянка"
      date: 2014-09-14 17:00:00

    - name: 'KOBYZHCHA MOTOFEST'
      url: http://vk.com/moto_petrovich_party
      location: село Кобижча, Бобровицкого ройона, Черниговской области
      date: 2014-08-23 15:00:00

    - name: 'Благотворительный фестиваль "Пикник на обочине"'
      url: http://vk.com/picnik_na_obochine
      location: Обухов, Городской пляж
      date: 2014-08-16 12:00:00

    - name: 'Благодійний Концерт "Заради миру, заради життя!"'
      location: Киев, Арт-паб "Бочка на Подолi"
      date: 2014-07-29 18:00:00
      url: http://vk.com/event73360405

    - name: 'Kiev Kills Metal Fest 2014'
      location: Киев, пр.Победы 112, клуб "Бинго"
      date: 2014-07-21 18:00:00
      url: http://vk.com/kievkills_metalsummer

    - name: 'EASTER METAL EGGS'
      location: Киев, Арт-паб "Бочка на Подолi"
      date: 2014-04-20 18:00:00
      url: http://vk.com/event69159173

    - name: 'MARCH METAL CATS III'
      location: Киев, байк-Rock&Roll-клуб "Route66"
      date: 2014-03-23 18:00:00
      url: http://vk.com/event63580017

    - name: 'Благодійний Концерт Пам`яті "Небесної Сотні"'
      location: Киев, Арт-паб "Бочка на Подолi"
      date: 2014-03-02 18:00:00
      url: http://vk.com/event67127595

    - name: 'ATMOSPHERIC WEEKEND TOUR'
      location: Кривой Рог, Металлургов пр. 12, Клуб "Madisan"
      date: 2014-02-08 18:00:00
      url: http://vk.com/awt_kr

    - name: 'Мото-рок-фест «ЧИСТАЯ ПЛАНЕТА»'
      location: Киев, байк-Rock&Roll-клуб "Route66"
      date: 2014-02-02 19:00:00
      url: http://vk.com/event63515388

    - name: 'METAL IN CITY'
      location: Чернигов, ул. Рокоссовского 53, Рок-клуб "Паук"
      date: 2014-01-25 18:00:00
      url: http://vk.com/metal_in_city

    - name: 'Киев - Total Metal Domination Tour, pt. 2'
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2013-11-16 18:00:00
      url: http://vk.com/tmd2_kiev

    - name: 'Kiev Kills: BC Rich Rock Contest 2013 - 2 отборочный тур'
      location: Киев, пр-т Победы 47, "City Pub"
      date: 2013-10-20 18:00:00
      url: http://vk.com/bcrich_2

    - name: 'Real Rock Show 2013 in Barvy'
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2013-09-14 18:00:00
      url: http://vk.com/realrockshowinbarvy2013

    - name: 'Metal Force Open Air Fest 2013'
      location: Житомир, "Клетка"
      date: 2013-08-31 18:00:00
      url: http://vk.com/mf_openair2013

    - name: 'Iron Heart GIG'
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2013-05-11 18:00:00
      url: http://vk.com/event53364922

    - name: 'MARCH METAL CATS FEST II '
      location: Киев, пр.Победы 112, клуб "Бинго"
      date: 2013-03-23 18:00:00
      url: http://vk.com/event46299826

    - name: 'pre-partys of MARCH METAL CATS FEST'
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2013-02-10 18:00:00
      url: http://vk.com/prepartysofmmcf

    - name: 'Kiev Kills - Secret Gathering Party'
      location: Киев, Ковальский пер.5, клуб "Барвы"
      date: 2013-01-19 19:00:00 
      url: http://vk.com/kievkills_secretgatheringparty

    - name: 'LIVE IN PRIME Фінал!! (3 сезон)'
      location: Киев, Кyдpявcький yзвіз 5-б, клyб "Пpaйм"
      date: 2012-11-30 18:00:00
      url: http://vk.com/event44889851

    - name: 'LIVE IN PRIME 1/2 фіналу (3 сезон)'
      location: Киев, Кyдpявcький yзвіз 5-б, клyб "Пpaйм"
      date: 2012-10-31 18:00:00
      url: http://vk.com/event43939378

    - name: 'Kiev Kills: Gothic Pain Party'
      location: Киев, Кyдpявcький yзвіз 5-б, клyб "Пpaйм"
      date: 2012-10-06 18:00:00
      url: http://vk.com/kievkillsgothicpainparty

    - name: 'LIVE IN PRIME 1/4 фіналу (3 сезон)'
      location: Киев, Кyдpявcький yзвіз 5-б, клyб "Пpaйм"
      date: 2012-09-25 18:00:00
      url: http://vk.com/event42633869
